# Generated by Django 5.0.2 on 2024-02-13 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_lead_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='org',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='webapp.userprofile'),
            preserve_default=False,
        ),
    ]
